### ISSUE TITLE
Pop-up de complétion d'exercice

### ISSUE THREAD

**Issue by Androz2091** [students-4-students/prog-labs-website#1]
Quand un exercice est complété, une pop-up s'affichera pour afficher deux boutons "Menu" et "Exercice Suivant"

**Comment by Mw3y** [comment]
Résolu avec [Add tests interface and functionalities](https://github.com/students-4-students/prog-labs-website/pull/29/commits/10864af18eba29bc5fcc7b1176e4b3446fe69121)
