### ISSUE TITLE
Intégration Godbolt

### ISSUE THREAD

**Issue by Androz2091** [students-4-students/prog-labs-website#2]
Lorsque l'utilisateur souhaite exécuter le code, une requête doit être envoyée à Godbolt pour récupérer l'output, afficher les erreurs, etc. et passer les tests

**Comment by Mw3y** [comment]
Résolu avec [Add tests interface and functionalities](https://github.com/students-4-students/prog-labs-website/pull/29/commits/10864af18eba29bc5fcc7b1176e4b3446fe69121)
