### ISSUE TITLE
Changer le style des doubles =

### ISSUE THREAD

**Issue by Androz2091** [students-4-students/prog-labs-website#46]
![image](https://github.com/user-attachments/assets/2fbafbde-f68f-4fe4-8a46-a747bbc191ae)

On ne voit paa assez la différence entre = et ==, et les gens pourraient ne pas comprendre que l'on fait référence à != avec le ≠

![image](https://github.com/user-attachments/assets/99e55391-2fba-4252-88d5-fa082919907f)

**Comment by Nicolapps** [comment]
On utilise Fira Code comme police pour le code ? Cette police c'est Fira Mono avec des ligatures, on devrait remplacer ça par Fira Mono (qui est la même que Fira Code mais sans les ligatures)

**Comment by Androz2091** [comment]
@Nicolapps je viens de fix ahah désolé :grimacing:
