### ISSUE TITLE
Les erreurs sortent de Monaco

### ISSUE THREAD

**Issue by Androz2091** [students-4-students/prog-labs-website#55]
![image](https://github.com/user-attachments/assets/2d4df8b3-facf-4196-9990-18a85bca43a8)

**Comment by Androz2091** [comment]
très low priority

**Comment by Mw3y** [comment]
À mon avis, c'est mieux ainsi.

**Comment by Androz2091** [comment]
ouai en vrai chiant si ça sort et ça se met par dessus la navbar
